import type {Verdict} from './core';
import {radar} from './radar';
import {stashActions} from './stash-actions';
import {agentBrief,extractPostUrl,STASH_URL} from './favstash';
export const badgeCSS=`
:host{all:initial;display:block;position:relative;z-index:1;color:#13192c;font:12px/1.5 'WMS Sora','Sora',Arial,sans-serif}
*{box-sizing:border-box}button,a,input{font:inherit}button{cursor:pointer}button:focus-visible,a:focus-visible{outline:2px solid #466fd2;outline-offset:3px}.bar{display:flex;align-items:center;gap:8px;padding:10px 14px;background:var(--wash);border-radius:9px 9px 0 0;color:#13192c;border-bottom:1px solid var(--line);min-height:42px}
.dot{width:6px;height:6px;border-radius:50%;background:var(--ink)}.label{font-size:11px;font-weight:600}.score{font-size:11px;font-weight:600;color:var(--ink);border-radius:5px;background:var(--wash);padding:2px 5px}.powered{display:none}.why{margin-left:0;border:1px solid #dfe5f0;color:#69718a;background:#fff;padding:4px 8px;border-radius:5px;font-size:10px;white-space:nowrap}.why:hover{color:#3458a8;border-color:#6f96ed}.recreate-chip{border:0;border-left:1px solid #e7ebf4;background:none;color:#466fd2;font-size:10px;padding:2px 0 2px 10px;white-space:nowrap}
.details{position:fixed;inset:auto;margin:0;width:340px;max-width:calc(100vw - 20px);max-height:calc(100vh - 24px);overflow:auto;overscroll-behavior:contain;border:1px solid #dce3f0;border-radius:16px;background:#fff;color:#13192c;padding:20px;box-shadow:0 16px 55px #13192c26;font:12px/1.5 'WMS Sora','Sora',Arial,sans-serif}.details::backdrop{background:transparent}.panel-head{display:flex;justify-content:space-between;align-items:start}.kicker{font-size:9px;letter-spacing:1.2px;color:#858da3;text-transform:uppercase}.headline{font-size:16px;font-weight:600;margin:5px 0 0}.close{border:0;background:#f6f8fc;border-radius:50%;width:26px;height:26px;color:#69718a;font-size:16px}.summary{display:flex;align-items:center;gap:13px;margin-top:17px}.big-score{font-size:34px;line-height:1;color:var(--ink);letter-spacing:-1px}.summary-label{font-size:11px;color:#69718a}.summary-label b{font-size:12px;color:#13192c;font-weight:600;display:block}.chart{margin:0 -4px}.chart svg{display:block;width:100%;height:210px}.chart-caption{font-size:9px;color:#858da3;text-align:center;margin-top:-4px;margin-bottom:16px}.metrics{display:grid;gap:9px;padding:14px 0;border-top:1px solid #edf0f6;border-bottom:1px solid #edf0f6}.metric{display:grid;grid-template-columns:85px 1fr 30px;align-items:center;gap:10px;font-size:10px;color:#69718a}.metric strong{font-size:10px;font-weight:500;text-align:right;color:#13192c}.track{height:4px;background:#edf1f8;border-radius:10px;overflow:hidden}.track i{display:block;height:100%;background:#6f96ed;border-radius:10px}.reasons{margin:14px 0;padding-left:15px;font-size:10px;color:#69718a}.reasons li{margin:5px 0}.note{font-size:9px;color:#858da3;margin:12px 0}.dismiss{background:transparent;border:0;color:#69718a;font-size:10px;text-decoration:underline;padding:6px 0}.stash-panel{border-radius:10px;background:#f6f8fc;padding:12px;display:flex;gap:8px;flex-wrap:wrap;align-items:center;font-size:10px}.stash-panel b{color:#3458a8;font-size:11px}.stash-panel a{color:#9b3f8c;font-size:10px;margin-left:auto;text-decoration:none}.stash-panel button{background:white;border:1px solid #dce3f0;border-radius:6px;padding:7px 9px;font-size:9px;color:#3458a8}.stash-panel button:disabled{opacity:.55}.link-fallback{padding:12px;background:#f6f8fc;border-radius:8px;font-size:10px}
.stash-actions{margin-left:auto;display:flex;align-items:center;gap:6px;flex-shrink:0}.save-stash{border:1px solid #dce3f0;border-radius:5px;padding:4px 8px;background:#f6f8fc;color:#3458a8;font-size:10px;white-space:nowrap}.save-stash:hover{background:#eff4fc;border-color:#6f96ed}.save-stash:disabled{opacity:.5;cursor:default}.stash-info{width:18px;height:18px;padding:0;border:1px solid #dce3f0;border-radius:50%;color:#858da3;background:#fff;font-size:10px}.stash-info:hover{color:#9b3f8c;border-color:#f09de5}.stash-info-panel,.stash-link-panel{width:310px;font-size:11px;line-height:1.8}.stash-info-panel .headline{font-size:14px;max-width:220px;line-height:1.5}.stash-info-panel p,.stash-link-panel p{color:#69718a}.stash-info-panel ol{padding-left:17px;color:#69718a}.stash-info-panel li{padding-left:3px;margin:9px 0}.stash-info-panel a{color:#466fd2;text-decoration:none;font-weight:600}.stash-link-panel label{display:block;font-size:10px;color:#69718a}.stash-link-panel input{display:block;width:100%;margin:6px 0 14px;padding:9px;border:1px solid #dce3f0;border-radius:6px}.stash-link-panel .dismiss{margin-left:12px}.stash-notice{color:#ba4637!important}.bar{flex-wrap:wrap}.bar .recreate-chip{flex-shrink:0}
@media(max-width:500px){.bar{gap:6px;padding:9px 10px}.recreate-chip{font-size:9px}.label{font-size:10px}}
`;
export function mountBadge(post:HTMLElement,verdict:Verdict,onDismiss?:()=>void,container?:HTMLElement){
 if(!container)post.querySelector(':scope > wms-rating')?.remove();
 const colors={green:['#1b7548','#e7f5ec','#8acda4'],amber:['#936216','#fff4d9','#e4c06f'],red:['#ba4637','#fdebe7','#e7a395']}[verdict.tone];
 post.style.setProperty('--wms-outline',colors[2]);post.classList.add('wms-rated');
 const host=document.createElement('wms-rating');const root=host.attachShadow({mode:'open'});
 host.style.setProperty('--ink',colors[0]);host.style.setProperty('--wash',colors[1]);host.style.setProperty('--line',colors[2]);
 const style=document.createElement('style');style.textContent=badgeCSS;root.append(style);
 const bar=document.createElement('div');bar.className='bar';
 const dot=document.createElement('span');dot.className='dot';dot.setAttribute('aria-hidden','true');
 const label=document.createElement('span');label.className='label';label.textContent=verdict.label;
 const score=document.createElement('span');score.className='score';score.textContent=`${verdict.score}/100`;score.title='Personal utility score out of 100';
 const powered=document.createElement('span');powered.className='powered';powered.textContent='JEV / WMS';
 const why=document.createElement('button');why.className='why';why.textContent='Why?';why.setAttribute('aria-expanded','false');
 bar.append(dot,label,score,powered,why);root.append(bar);
 const actions=stashActions(root,post,verdict);bar.insertBefore(actions,why);
 let stashPanel:HTMLElement|undefined;
 if(verdict.fit>=60&&verdict.substance>=50&&verdict.recreate>=50){
  const chip=document.createElement('button');chip.className='recreate-chip';chip.textContent=`✦ Recreate ${verdict.recreate}`;chip.title='Recreation potential · FavStash';chip.onclick=()=>why.click();bar.insertBefore(chip,actions);
  const stash=document.createElement('div');stash.className='stash-panel';stashPanel=stash;
  const recreate=document.createElement('b');recreate.textContent=`✦ Recreate ${verdict.recreate}/100`;recreate.title='Potential for an original post using your own experience. Not a virality forecast.';
  const brand=document.createElement('a');brand.textContent='FavStash';brand.href=STASH_URL;brand.target='_blank';brand.rel='noopener noreferrer';brand.style.cssText='color:#3458a8;text-decoration:none;font-weight:700;margin-right:auto';
  const source=extractPostUrl(post);
  const brief=document.createElement('button');brief.textContent='Copy agent brief';
  brief.onclick=async()=>{try{const text=post.querySelector('.post-text, [data-testid="expandable-text-box"], .update-components-text, .feed-shared-update-v2__description')?.textContent||'';await navigator.clipboard.writeText(agentBrief(text,verdict,source));brief.textContent='Brief copied ✓';}catch{brief.textContent='Clipboard unavailable';}};
  stash.append(recreate,brand,brief);
 }
 const details=document.createElement('div');details.className='details';details.setAttribute('popover','auto');details.setAttribute('role','dialog');details.setAttribute('aria-label','Why this post?');
 const head=document.createElement('div');head.className='panel-head';const title=document.createElement('div');const kicker=document.createElement('div');kicker.className='kicker';kicker.textContent='WORTH MY SCROLL';const headline=document.createElement('div');headline.className='headline';headline.textContent='Your signal profile';title.append(kicker,headline);const close=document.createElement('button');close.className='close';close.textContent='×';close.setAttribute('aria-label','Close analysis');head.append(title,close);
 const summary=document.createElement('div');summary.className='summary';const big=document.createElement('div');big.className='big-score';big.textContent=String(verdict.score);const summaryLabel=document.createElement('div');summaryLabel.className='summary-label';const outcome=document.createElement('b');outcome.textContent=verdict.label;summaryLabel.append(outcome,document.createTextNode('Personal utility / 100'));summary.append(big,summaryLabel);
 const chart=document.createElement('div');chart.className='chart';chart.append(radar(verdict));const caption=document.createElement('div');caption.className='chart-caption';caption.textContent='Larger shape = stronger signal for you';
 const metrics=document.createElement('div');metrics.className='metrics';
 for(const [name,value] of [['Personal fit',verdict.fit],['Substance',verdict.substance],['Practical value',verdict.value],['Slop',verdict.slop],['Bait',verdict.bait],['Recreate',verdict.recreate]] as const){const row=document.createElement('div');row.className='metric';const label=document.createElement('span');label.textContent=name;const track=document.createElement('div');track.className='track';const fill=document.createElement('i');fill.style.width=`${value}%`;if(name==='Slop'||name==='Bait')fill.style.background='#d98d85';track.append(fill);const number=document.createElement('strong');number.textContent=String(value);row.append(label,track,number);metrics.append(row);}
 const reasons=document.createElement('ul');reasons.className='reasons';for(const text of verdict.reasons){const li=document.createElement('li');li.textContent=text;reasons.append(li);}
 const note=document.createElement('p');note.className='note';note.textContent=`${verdict.cached?'Cached':`${(verdict.ms/1000).toFixed(2)}s`} · Jev${verdict.confidence!==undefined?` · Model confidence ${verdict.confidence}%`:''}. Visible text only. Slop is not proof of AI authorship; recreate is not a virality forecast.`;note.title='Model confidence is the average reported score confidence, not measured accuracy.';
 const dismiss=document.createElement('button');dismiss.className='dismiss';dismiss.textContent='Clear this rating';dismiss.onclick=()=>{details.hidePopover();host.remove();post.classList.remove('wms-rated');post.style.removeProperty('--wms-outline');onDismiss?.();};
 details.append(head,summary,chart,caption,metrics,reasons);if(stashPanel)details.append(stashPanel);details.append(note,dismiss);root.append(details);
 close.onclick=()=>details.hidePopover();
 details.addEventListener('toggle',()=>why.setAttribute('aria-expanded',String(details.matches(':popover-open'))));
 why.onclick=()=>{if(details.matches(':popover-open')){details.hidePopover();return;}details.showPopover();const r=why.getBoundingClientRect();details.style.left=`${Math.max(10,Math.min(innerWidth-350,r.right-340))}px`;const height=details.getBoundingClientRect().height;details.style.top=`${Math.max(12,Math.min(innerHeight-height-12,r.bottom+8))}px`;close.focus({preventScroll:true});};
 if(container)container.append(host);else post.prepend(host);return host;
}
